package model;
// Generated 20-ene-2020 16:13:16 by Hibernate Tools 5.4.7.Final

/**
 * ClassId generated by hbm2java
 */
public class ClassId implements java.io.Serializable {

	private int classId;
	private String className;

	public ClassId() {
	}

	public ClassId(int classId, String className) {
		this.classId = classId;
		this.className = className;
	}

	public int getClassId() {
		return this.classId;
	}

	public void setClassId(int classId) {
		this.classId = classId;
	}

	public String getClassName() {
		return this.className;
	}

	public void setClassName(String className) {
		this.className = className;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ClassId))
			return false;
		ClassId castOther = (ClassId) other;

		return (this.getClassId() == castOther.getClassId())
				&& ((this.getClassName() == castOther.getClassName()) || (this.getClassName() != null
						&& castOther.getClassName() != null && this.getClassName().equals(castOther.getClassName())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getClassId();
		result = 37 * result + (getClassName() == null ? 0 : this.getClassName().hashCode());
		return result;
	}

}
