package model;
// Generated 20-ene-2020 16:13:16 by Hibernate Tools 5.4.7.Final

/**
 * Device generated by hbm2java
 */
public class Device implements java.io.Serializable {

	private DeviceId id;

	public Device() {
	}

	public Device(DeviceId id) {
		this.id = id;
	}

	public DeviceId getId() {
		return this.id;
	}

	public void setId(DeviceId id) {
		this.id = id;
	}

}
