package model;
// Generated 20-ene-2020 16:13:16 by Hibernate Tools 5.4.7.Final

/**
 * Weapon generated by hbm2java
 */
public class Weapon implements java.io.Serializable {

	private WeaponId id;

	public Weapon() {
	}

	public Weapon(WeaponId id) {
		this.id = id;
	}

	public Weapon(int i, String string, String string2, int j, int k) {
		// TODO Auto-generated constructor stub
	}

	public WeaponId getId() {
		return this.id;
	}

	public void setId(WeaponId id) {
		this.id = id;
	}

}
